[package]
name = "forest-fire"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.2"
yew = "0.19"
wasm-bindgen = "0.2"
gloo = "0.8"
pulldown-cmark = "0.9.2"
walkdir = "2"
gray_matter = "0.2.4"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
]